services:
  - type: web
    name: ca-trans-devis
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ORS_API_KEY
        sync: false
